### ISSUE TITLE
Fractal Card Info Unable to be Copied

### ISSUE THREAD

**Issue by Rizz0S** [SeanWelshBrown/the-fractal-zone-frontend#16]
When a fractal pattern is clicked, information about the pattern's params (axiom, rule set, theta etc) is displayed in an overlay. However, since this is an on-click event, when a user tries to click & drag to copy information, the overlay disappears.

![tfz-overlay-cick-issue](https://user-images.githubusercontent.com/39225869/87859924-0d1a4180-c907-11ea-9d90-5c236912f237.gif)

**Comment by SeanWelshBrown** [comment]
Thanks for pointing this out!

I went in and changed our onClick function that was being called in the FractalCard component when the image was clicked, checking to see if there's currently a selection in the window-- ignoring the state change if so, and carrying through with it like normal if not.

```
const handleCardClick = () => {
  const selection = window.getSelection();
  if (selection.type !== "Range") {
    setClicked(!isClicked)
  }
}
```
